[package]
name = "cgt_math"
version = "0.0.1"
edition = "2021"
authors = ["Denys Hsu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
